# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92c68ac96d3b1cb362d663963b3e8b708dd71bf82368ac0d1e84152931f1b682b5d03b6bc7ba7f177c52514f32ac73ea4eff55e56b428077352f4190309f0a06

test:
  secret_key_base: c130c26b2c85b1971db10c207693081a044ddcf7dc8e7e8efa7840f1129fbf658d05a2e4c195f5d7078d9924d1d4a91a7a2e63aa0bd70580f6028bcd378cfed6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
